### ISSUE TITLE
Big skips can fail with io.ErrNoProgress

### ISSUE THREAD

**Issue by klauspost** [philhofer/fwd#20]
This shows up in [the code here](https://github.com/minio/minio/blob/ca88ca753c5832b62d746cd236e2fa46acfe9f61/cmd/metacache-stream.go#L384) when using msgp.

This is a stream with `bool`, `string`, `[]byte`.

We read the bool and the string and depending on the string we usually just skip reading the byte array. I manually read the string into a byte slice to avoid having to allocate since we want to be able to skip forward as fast as possible.

The input is not seekable, so the reader ends up in [this piece of code](https://github.com/philhofer/fwd/blob/414ae1bb9ed152f441b372db076776b3a937ebf5/reader.go#L220) when there isn't `n` bytes buffered.

The problem is that it calls [`more`](https://github.com/philhofer/fwd/blob/414ae1bb9ed152f441b372db076776b3a937ebf5/reader.go#L107) at once and in cases where `len(r.data) == cap(r.data)` if the buffer is already full, but Skip wants to skip more bytes.

This leads to the request to be for 0 bytes and `if a == 0 && r.state == nil`  will be true, causing the `io.ErrNoProgress`.

I will create a PR with a proposal for a fix.

Ref: https://github.com/minio/minio/issues/10959

**Comment by klauspost** [comment]
Sorry for the bad descriptions. I hope you can make out what I mean ;)

**Comment by philhofer** [comment]
Thanks for filing this issue!
