### ISSUE TITLE
tag a new release

### ISSUE THREAD

**Issue by thaJeztah** [philhofer/fwd#27]
While going through our dependency tree, I noticed that this module has some fixes in the main branch that have not yet made their way into a release (at time of writing: https://github.com/philhofer/fwd/compare/v1.1.1...b411808a24253af9235385bcbaf6896a873a18ec), which includes a fix for a potential panic, and fixes around handling of "unsafe".

I was wondering if a new release is planned 😅 

/cc @philhofer

**Comment by thaJeztah** [comment]
Also opened https://github.com/philhofer/fwd/pull/28, to fix some nits, and to make the "no valid go.mod" on pkg.go.dev happy.

**Comment by philhofer** [comment]
Tagged v1.1.2
