### ISSUE TITLE
LICENSE file

### ISSUE THREAD

**Issue by client9** [philhofer/fwd#7]
Hi phil.. great stuff.

Sadly, today Im working on the pleasing the Gods of Compliance. While tinylib/msgp is MIT licensed, it includes this other repo which doesn't have a license.  Could you drop one in?  Im happy to do a pull request, but that might be a bit odd since Im not the author.

thanks!

n

**Comment by philhofer** [comment]
Done and done.

Best,
Phil

**Comment by client9** [comment]
you rock
